### ISSUE TITLE
Add feedback messages for actions happening

### ISSUE THREAD

**Issue by MatheusMiranda** [MatheusMiranda/django-social-auth-app#14]
It's important to give to the user feedback about the actions happening on the application. There is no feedback of any kind on deletions, updates and creations actions.

**Tasks**
- [ ] Render form errors on submit;
- [ ] Add feedback for the user on Repository creation, update and deletion;
- [ ] Add feedback for the user on Tag creation;
- [ ] Add feedback for the user on login/logout.

**Comment by beingbiplov** [comment]
Hey there , I can work on this issue.

**Comment by MatheusMiranda** [comment]
@beingbiplov It would be very nice ;)
