### ISSUE TITLE
Create app for Tag

### ISSUE THREAD

**Issue by MatheusMiranda** [MatheusMiranda/django-social-auth-app#2]
Remove model *Tag* and related actions from *repository* app and insert in a new app *Tag*.

**Tasks**
- [ ] Create model *Tag*;
- [ ] Create app *Tag*;
- [ ] Migrate actions to the new view file.
