### ISSUE TITLE
Create CI pipeline

### ISSUE THREAD

**Issue by MatheusMiranda** [MatheusMiranda/django-social-auth-app#9]
Create a Continuous Integration pipeline to test project quality and avoid errors on development.

**Tasks**

- [ ] Create stage that run *flake8* on the project code;
- [ ] Create stage that test the generation and deploy of all the django migrations;
- [ ] Create stage that runs all the test tasks;
- [ ] Create stage that builds and deploy image for service 'web' to Dockerhub.

Depends on issues:
#5 #6 #7 #8 #11
